# Generated by Django 3.2.7 on 2021-09-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('dosen', models.CharField(max_length=100)),
                ('sks', models.PositiveIntegerField()),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], default='Ganjil', max_length=6)),
                ('tahun', models.CharField(choices=[('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023')], default='2019/2020', max_length=9)),
                ('ruang', models.CharField(max_length=20)),
                ('deskripsi', models.CharField(max_length=300)),
            ],
        ),
    ]
